image: node:18.7.0

before_script:
  - apt-get update -qq && apt-get install
  - node -v

stages:
  - deploy-to-staging
  - deploy-to-test
  - deploy-to-production

deploy-staging:
  tags:
    - vallentuna
    - backend
    - staging
  stage: deploy-to-staging
  environment:
    name: staging
    url: https://api.staging.vallentuna.su.eagle.productions
  before_script:
    - whoami
    - node --version
    - npm --version
  script:
    - bash deploy/staging.sh
  only:
    - staging

deploy-test:
  tags:
    - vallentuna
    - backend
    - test
  stage: deploy-to-test
  environment:
    name: test
    url: https://api.test.vallentuna.su.eagle.productions
  before_script:
    - whoami
    - node --version
    - npm --version
  script:
    - bash deploy/test.sh
  only:
    - test

deploy-production:
  tags:
    - vallentuna
    - backend
    - production
  stage: deploy-to-production
  environment:
    name: production
    url: https://api.vallentuna.su.eagle.productions
  before_script:
    - whoami
    - node --version
    - npm --version
  script:
  - bash deploy/production.sh
  only:
    - main