image: ubuntu:latest

stages:
  - deploy-to-production

nohttp:
  stage: check
  tags:
    - vallentuna
    - backend
deploy-production:
  stage: deploy-to-production
  environment:
    name: production
    url: https://vallentuna.su
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
  - bash deploy/deploy.sh
  only:
    - main