image: node:18.7.0

before_script:
  - apt-get update -qq && apt-get install
  - node -v

stages:
  - deploy-to-production

deploy-production:
  tags:
    - vallentuna
    - backend
    - production
  stage: deploy-to-production
  environment:
    name: production
    url: https://vallentuna.su
  before_script:
    - whoami
    - node --version
    - npm --version
    #- apt-get update -qy
    #- apt-get install -qy git
    #- 'which ssh-agent || ( apt-get install -qy openssh-client )'
    #- eval $(ssh-agent -s)
    #- ssh-add <(echo "$SSH_KEY")
    #- mkdir -p ~/.ssh
    #- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
  - bash deploy/production.sh
  only:
    - main