image: node:18.7.0

before_script:
  - apt-get update -qq && apt-get install
  - node -v

stages:
  - deploy-to-production

deploy-production:
  tags:
    - vallentuna
    - backend
    - production
  stage: deploy-to-production
  environment:
    name: production
    url: https://vallentuna.su
  before_script:
    - whoami
    - node --version
    - npm --version
  script:
  - bash deploy/production.sh
  only:
    - main