image: ubuntu:latest

stages:
  - deploy-to-development
  - deploy-to-production

deploy-development:
  tags:
    - vallentuna
    - backend
    - development
  stage: deploy-to-development
  environment:
    name: development
    url: https://development.vallentuna.su
  before_script:
    - whoami

    #- apt-get update -qy
    #- apt-get install -qy git
    #- 'which ssh-agent || ( apt-get install -qy openssh-client )'
    #- eval $(ssh-agent -s)
    #- ssh-add <(echo "$SSH_KEY")
    #- mkdir -p ~/.ssh
    #- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - bash deploy/development.sh
  only:
    - dev


deploy-production:
  tags:
    - vallentuna
    - backend
    - production
  stage: deploy-to-production
  environment:
    name: production
    url: https://vallentuna.su
  before_script:
    - whoami
    - node --version
    - npm --version
    - npm install
    #- apt-get update -qy
    #- apt-get install -qy git
    #- 'which ssh-agent || ( apt-get install -qy openssh-client )'
    #- eval $(ssh-agent -s)
    #- ssh-add <(echo "$SSH_KEY")
    #- mkdir -p ~/.ssh
    #- '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
  - bash deploy/production.sh
  only:
    - main