export const VALLENTUNA_SURVEY_BACKEND_APP_SECRET =
  process.env.VALLENTUNA_SURVEY_BACKEND_APP_SECRET;
export const VALLENTUNA_SURVEY_BACKEND_SSL_MODE =
  process.env.VALLENTUNA_SURVEY_BACKEND_SSL_MODE;
export const VALLENTUNA_SURVEY_BACKEND_PORT =
  process.env.VALLENTUNA_SURVEY_BACKEND_PORT;
export const VALLENTUNA_SURVEY_BACKEND_NODE_ENV =
  process.env.VALLENTUNA_SURVEY_BACKEND_NODE_ENV;
export const VALLENTUNA_SURVEY_BACKEND_ALLOWED_ORIGINS =
  process.env.VALLENTUNA_SURVEY_BACKEND_ALLOWED_ORIGINS;
export const POSTGRES_HOST = process.env.POSTGRES_HOST;
export const POSTGRES_PORT = process.env.POSTGRES_PORT;
export const POSTGRES_USER = process.env.POSTGRES_USER;
export const POSTGRES_PASS = process.env.POSTGRES_PASS;
export const POSTGRES_NAME = process.env.POSTGRES_NAME;
